uploads = []
generated = []

[[outputs]]
id = "KofESHoJFspnAB7V7FfXy"
uri = "file://attached_assets/kingdoms-conquest-FIXED.zip"
type = "unspecified"
title = "kingdoms-conquest-FIXED.zip"

[[outputs]]
id = "xOk5PdCpqdUcIzcLGiHsc"
uri = "file://KingdomsConquest.zip"
type = "unspecified"
title = "KingdomsConquest.mcaddon (download as zip, rename to .mcaddon)"

[[outputs]]
id = "HpkuWtgMcE3ZXEZVwpDLF"
uri = "file://KingdomsConquest_download.zip"
type = "unspecified"
title = "KingdomsConquest.mcaddon (download)"
